theme: jekyll-theme-minimal
title: Almudena Zhou Ramírez López
description: >
  <br><br>
  <br><br>
  <a href="https://es.linkedin.com/in/almudena-zhou-ramirez-lopez">My LinkedIn Profile</a>
  <a href="https://github.com/AlmudenaZhou">My GitHub</a>
  <a href="pdf/AlmudenaZhouRamirezLopezCVEnglish.pdf">CV</a>
