theme: jekyll-theme-minimal
title: Almudena Zhou Ramírez López
description: >
  <div>
  <a href="https://es.linkedin.com/in/almudena-zhou-ramirez-lopez">My LinkedIn</a>
  </div>
  <div>
  <a href="https://github.com/AlmudenaZhou">My GitHub</a>
  </div>
  <div>
  <a href="pdf/AlmudenaZhouRamirezLopezCVEnglish.pdf">CV</a>
  </div>

skills: >
  <div>
  Python: numpy, pandas, sklearn
  </div>
  <div>
  Databricks, Spark, MLFlow
  </div>
  <div>
  Azure
  </div>
  <div>
  LLMs, RAGs, fine-tuning
  </div>
  <div>
  Docker
  </div>
  <div>
  Terraform
  </div>

certifications: >
  <div>
  <a href="https://learn.microsoft.com/en-us/users/almudenazhouramrezlpez-9156/credentials/4c8f214d0262676a">Azure AI-102 certification</a>
  </div>
  <div>
  <a href="https://certificate.datatalks.club/dezoomcamp/2024/b1c7c7fc44002719bc87f4c166716cc5d828a858.pdf">Data Engineering Zoomcamp</a>
  </div>
