title: Almudena Zhou Ramírez López
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-tabs
  - jekyll-remote-theme
linkedin: almudena-zhou-ramirez-lopez
github: AlmudenaZhou
email: almudena.zhou.rl@gmail.com
social-links-order: [linkedin, github, email]
projects-order: [mlops_student_performance, gharchive_etl, factories_pygame]
collections:
  projects:
description: >
  <div class=about-me>
  I am an experienced Data Scientist and AI Engineer with a strong background in developing and deploying machine learning models with additional experience in prompting engineering, LLMs and RAGs. 
  </div>
  <br>
  <div>
  For more information: <a href="assets/pdf/AlmudenaZhouRamirezLopezCVEnglish.pdf">download my CV</a>
  </div>
logo: /assets/images/circle_profile_photo.png
certifications: >
  <div>
  <a href="https://learn.microsoft.com/en-us/users/almudenazhouramrezlpez-9156/credentials/4c8f214d0262676a">Azure AI-102 certification</a>
  </div>
  <div>
  <a href="https://certificate.datatalks.club/dezoomcamp/2024/b1c7c7fc44002719bc87f4c166716cc5d828a858.pdf">Data Engineering Zoomcamp</a>
  </div>
