title: Almudena Zhou Ramírez López
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-tabs
  - jekyll-remote-theme
linkedin: almudena-zhou-ramirez-lopez
github: AlmudenaZhou
email: almudena.zhou.rl@gmail.com
description: >
  <div>
  <a href="assets/pdf/AlmudenaZhouRamirezLopezCVEnglish.pdf">Download my CV</a>
  </div>

skills: >
  <div>
  Python: numpy, pandas, sklearn
  </div>
  <div>
  Databricks, Spark, MLFlow
  </div>
  <div>
  Azure
  </div>
  <div>
  LLMs, RAGs, fine-tuning
  </div>
  <div>
  Docker
  </div>
  <div>
  Terraform
  </div>

certifications: >
  <div>
  <a href="https://learn.microsoft.com/en-us/users/almudenazhouramrezlpez-9156/credentials/4c8f214d0262676a">Azure AI-102 certification</a>
  </div>
  <div>
  <a href="https://certificate.datatalks.club/dezoomcamp/2024/b1c7c7fc44002719bc87f4c166716cc5d828a858.pdf">Data Engineering Zoomcamp</a>
  </div>
