title: Almudena Zhou Ramírez López
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-tabs
  - jekyll-remote-theme
linkedin: almudena-zhou-ramirez-lopez
github: AlmudenaZhou
email: almudena.zhou.rl@gmail.com
social-links-order: [linkedin, github, email]
projects-order: [azureml_fine_food_reviews, cs_ds_interview_assistant, mlops_student_performance, gharchive_etl, factories_pygame]
collections:
  projects:
description: >
  <div class=about-me>
  Hi! I’m a Data Scientist and ML/AI Engineer passionate about building impactful machine learning solutions. I specialize in end-to-end machine learning workflows, large language models (LLMs), and retrieval-augmented generation (RAGs). My curiosity for exploring new technologies has given me a deep understanding of the entire data lifecycle.
  </div>
logo: /assets/images/circle_profile_photo.png
certifications: >
  <div>
  <a href="https://learn.microsoft.com/en-us/users/almudenazhouramrezlpez-9156/credentials/4c8f214d0262676a">Azure AI-102 certification</a>
  </div>
  <div>
  <a href="https://certificate.datatalks.club/llm-zoomcamp/2024/b1c7c7fc44002719bc87f4c166716cc5d828a858.pdf">LLM Zoomcamp</a>
  </div>
  <div>
  <a href="https://certificate.datatalks.club/mlops-zoomcamp/2024/b1c7c7fc44002719bc87f4c166716cc5d828a858.pdf">MLOps Zoomcamp</a>
  </div>
  <div>
  <a href="https://certificate.datatalks.club/dezoomcamp/2024/b1c7c7fc44002719bc87f4c166716cc5d828a858.pdf">Data Engineering Zoomcamp</a>
  </div>

cv-download: >
  <div>
  For more information: <a href="assets/pdf/AlmudenaZhouRamirezLopezCVEnglish.pdf">download my CV</a>
  </div>